const QUESTIONS = [
  {
    id: 1,
    type: "mcq",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt:
      "Di sekolah terdapat siswa dari berbagai agama. Saat perayaan hari besar keagamaan, seluruh siswa saling membantu menjaga keamanan dan kebersihan acara. Konfigurasi kemajemukan yang tampak adalah...",
    options: ["konflik sosial", "integrasi sosial", "dominasi kelompok mayoritas", "fragmentasi sosial"],
    answer: 1,
    explanation:
      "Situasi menunjukkan kerja sama lintas kelompok dan keterpaduan sosial, sehingga paling tepat disebut integrasi sosial.",
  },
  {
    id: 2,
    type: "match",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt: "Jodohkan konsep dengan pernyataannya.",
    left: ["Segmentasi", "Dominasi", "Kompetisi Seimbang", "Fragmentasi"],
    right: [
      "Kelompok-kelompok sosial terpisah berdasarkan identitas tertentu",
      "Satu kelompok menguasai kelompok lain",
      "Tidak ada kelompok yang terlalu berkuasa",
      "Sulit tercipta persatuan antarkelompok",
    ],
    pairs: [0, 1, 2, 3],
    explanation:
      "Segmentasi = terpisah, dominasi = menguasai, kompetisi seimbang = tidak ada yang dominan, fragmentasi = sulit bersatu.",
  },
  {
    id: 3,
    type: "multi",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt:
      "Di suatu daerah, jabatan pemerintahan hampir seluruhnya diisi oleh etnis mayoritas. Pernyataan yang tepat:",
    options: [
      "Terjadi dominasi",
      "Kesempatan politik tidak merata",
      "Menunjukkan kompetisi seimbang",
      "Berpotensi memicu kecemburuan sosial",
    ],
    answer: [0, 1, 3],
    explanation:
      "Situasi itu menunjukkan dominasi, ketidakmerataan kesempatan, dan potensi kecemburuan sosial. Bukan kompetisi seimbang.",
  },

  {
    id: 4,
    type: "mcq",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt:
      "Dalam tim kerja, keputusan selalu ditentukan oleh kelompok kecil tertentu walaupun jumlah mereka sedikit. Dampak yang mungkin terjadi adalah...",
    options: ["solidaritas meningkat", "konflik antarkelompok", "integrasi semakin kuat", "produktivitas selalu meningkat"],
    answer: 1,
    explanation:
      "Dominasi kelompok kecil cenderung memunculkan ketidakpuasan dan konflik antarkelompok.",
  },

  {
    id: 5,
    type: "multi",
    topic: "Diferensiasi Sosial",
    prompt: "Yang termasuk diferensiasi sosial adalah...",
    options: ["Perbedaan agama", "Perbedaan suku", "Perbedaan profesi", "Perbedaan kelas ekonomi"],
    answer: [0, 1, 2],
    explanation:
      "Diferensiasi sosial adalah perbedaan yang sifatnya horizontal, misalnya agama, suku, dan profesi. Kelas ekonomi adalah stratifikasi.",
  },
  {
    id: 6,
    type: "mcq",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt: "Manakah contoh masyarakat multikultural di Indonesia?",
    options: [
      "Desa yang seluruh penduduknya berasal dari satu suku",
      "Kota yang dihuni berbagai suku, agama, dan budaya",
      "Kelompok keluarga inti",
      "Organisasi sekolah",
    ],
    answer: 1,
    explanation:
      "Masyarakat multikultural ditandai oleh keanekaragaman suku, agama, budaya, dan latar sosial dalam satu ruang hidup.",
  },
  {
    id: 7,
    type: "mcq",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt: "Cara paling tepat mengatasi dominasi dalam perusahaan multinasional adalah...",
    options: [
      "membatasi pegawai minoritas",
      "membiarkan kondisi berlangsung",
      "memberikan kesempatan yang setara dalam pengambilan keputusan",
      "menghapus seluruh aturan perusahaan",
    ],
    answer: 2,
    explanation:
      "Harmoni sosial dicapai melalui kesetaraan akses dan partisipasi dalam pengambilan keputusan.",
  },
  {
    id: 8,
    type: "multi",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt: "Tantangan kebijakan afirmasi berbasis etnis adalah...",
    options: ["Kecemburuan sosial", "Diskriminasi terbalik", "Meningkatkan integrasi otomatis", "Sulit menentukan batas kelompok penerima"],
    answer: [0, 1, 3],
    explanation:
      "Kebijakan afirmasi dapat memunculkan kecemburuan, diskriminasi terbalik, dan persoalan penentuan penerima kebijakan.",
  },
  {
    id: 9,
    type: "mcq",
    topic: "Masyarakat Majemuk & Multikultural",
    prompt: "Perebutan ruang publik di kota besar sering terjadi karena...",
    options: ["homogenitas masyarakat", "keterbatasan sumber daya dan kepentingan berbeda", "tidak adanya penduduk", "budaya yang sama"],
    answer: 1,
    explanation:
      "Konflik ruang publik biasanya dipicu keterbatasan sumber daya dan perbedaan kepentingan antarpelaku sosial.",
  },

  {
    id: 10,
    type: "mcq",
    topic: "Stratifikasi Sosial",
    prompt: "Anak seorang raja otomatis menjadi bangsawan. Status tersebut termasuk...",
    options: ["achieved status", "assigned status", "ascribed status", "acquired status"],
    answer: 2,
    explanation: "Status yang diperoleh sejak lahir atau keturunan adalah ascribed status.",
  },
  {
    id: 11,
    type: "multi",
    topic: "Stratifikasi Sosial",
    prompt: "Pak Anton adalah dokter, ketua RT, dan ayah dari dua anak. Status sosial yang dimiliki Pak Anton adalah...",
    options: ["Dokter", "Ketua RT", "Ayah", "Tinggi badan"],
    answer: [0, 1, 2],
    explanation: "Seseorang bisa memiliki banyak status sosial sekaligus. Tinggi badan bukan status sosial.",
  },
  {
    id: 12,
    type: "mcq",
    topic: "Stratifikasi Sosial",
    prompt: "Sistem stratifikasi sosial terbuka memberikan dampak positif berupa...",
    options: ["kesempatan berprestasi lebih besar", "mobilitas sosial tertutup", "keturunan menentukan seluruh status", "tidak ada perubahan status"],
    answer: 0,
    explanation: "Stratifikasi terbuka mendorong mobilitas sosial dan kesempatan berprestasi.",
  },
  {
    id: 13,
    type: "match",
    topic: "Stratifikasi Sosial",
    prompt: "Jodohkan jenis status dengan contohnya.",
    left: ["Ascribed Status", "Achieved Status", "Assigned Status"],
    right: ["Ketua OSIS terpilih", "Gelar pahlawan nasional", "Anak bangsawan"],
    pairs: [2, 0, 1],
    explanation:
      "Ascribed = bawaan lahir, achieved = hasil usaha, assigned = pemberian/penghargaan sosial.",
  },
  {
    id: 14,
    type: "mcq",
    topic: "Stratifikasi Sosial",
    prompt: "Ciri utama stratifikasi sosial terbuka adalah...",
    options: ["status ditentukan kelahiran", "perpindahan status memungkinkan", "kasta berlaku ketat", "tidak ada mobilitas sosial"],
    answer: 1,
    explanation: "Stratifikasi terbuka memungkinkan perpindahan status melalui usaha dan prestasi.",
  },

  {
    id: 15,
    type: "mcq",
    topic: "Diferensiasi Sosial",
    prompt: "Yang merupakan diferensiasi sosial adalah...",
    options: ["kaya dan miskin", "direktur dan karyawan", "guru dan dokter", "atasan dan bawahan"],
    answer: 2,
    explanation: "Guru dan dokter adalah perbedaan profesi, yaitu diferensiasi sosial.",
  },
  {
    id: 16,
    type: "mcq",
    topic: "Mobilitas Sosial",
    prompt: "Seorang pegawai menjadi manajer karena prestasinya. Contoh tersebut merupakan...",
    options: ["mobilitas horizontal", "mobilitas vertikal naik", "mobilitas vertikal turun", "diferensiasi sosial"],
    answer: 1,
    explanation: "Peningkatan kedudukan dari pegawai menjadi manajer merupakan mobilitas vertikal naik.",
  },
  {
    id: 17,
    type: "multi",
    topic: "Stratifikasi Sosial",
    prompt: "Ciri stratifikasi terbuka:",
    options: ["Mobilitas sosial tinggi", "Kesempatan berprestasi", "Status ditentukan keturunan", "Perubahan kedudukan dimungkinkan"],
    answer: [0, 1, 3],
    explanation:
      "Ciri stratifikasi terbuka adalah mobilitas tinggi, kesempatan berprestasi, dan perubahan status dimungkinkan.",
  },
  {
    id: 18,
    type: "multi",
    topic: "Mobilitas Sosial",
    prompt: "Faktor penghambat mobilitas sosial:",
    options: ["Kemiskinan", "Pendidikan rendah", "Diskriminasi", "Prestasi tinggi"],
    answer: [0, 1, 2],
    explanation:
      "Kemiskinan, pendidikan rendah, dan diskriminasi menghambat mobilitas sosial. Prestasi tinggi justru mendorong mobilitas.",
  },
  {
    id: 19,
    type: "match",
    topic: "Mobilitas Sosial",
    prompt: "Jodohkan bentuk mobilitas dengan kasusnya.",
    left: ["Mobilitas Vertikal Naik", "Mobilitas Vertikal Turun", "Mobilitas Horizontal"],
    right: ["Guru pindah sekolah dengan jabatan sama", "Direktur menjadi staf biasa", "Karyawan menjadi manajer"],
    pairs: [2, 1, 0],
    explanation:
      "Naik = status naik, turun = status turun, horizontal = kedudukan sama tetapi lokasi/posisi berubah.",
  },
  {
    id: 20,
    type: "mcq",
    topic: "Mobilitas Sosial",
    prompt: "Contoh mobilitas vertikal naik adalah...",
    options: ["siswa pindah sekolah", "petani menjadi kepala desa", "dokter pindah rumah sakit", "guru pindah kota"],
    answer: 1,
    explanation: "Petani menjadi kepala desa menunjukkan peningkatan status sosial.",
  },

  {
    id: 21,
    type: "multi",
    topic: "Diferensiasi Sosial",
    prompt: "Dampak positif diferensiasi sosial:",
    options: ["Toleransi meningkat", "Kerja sama antarkelompok", "Konflik selalu terjadi", "Kekayaan budaya"],
    answer: [0, 1, 3],
    explanation:
      "Diferensiasi yang dikelola dengan baik dapat meningkatkan toleransi, kerja sama, dan kekayaan budaya.",
  },
  {
    id: 22,
    type: "mcq",
    topic: "Diferensiasi Sosial",
    prompt: "Peran ganda perempuan dapat menyebabkan...",
    options: ["beban kerja berlebihan", "integrasi sempurna", "konflik hilang", "status sosial menurun otomatis"],
    answer: 0,
    explanation:
      "Peran ganda dapat menimbulkan beban fisik dan psikologis karena tuntutan di ranah domestik dan publik.",
  },

  {
    id: 23,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Yang mencerminkan nilai material adalah...",
    options: ["mobil mewah", "kejujuran", "kasih sayang", "religiusitas"],
    answer: 0,
    explanation: "Nilai material berkaitan dengan benda fisik yang berguna bagi kehidupan.",
  },
  {
    id: 24,
    type: "match",
    topic: "Nilai dan Norma Sosial",
    prompt: "Jodohkan jenis nilai dengan contohnya.",
    left: ["Nilai Material", "Nilai Vital", "Nilai Rohani"],
    right: ["Laptop untuk bekerja", "Keimanan", "Rumah mewah"],
    pairs: [2, 0, 1],
    explanation:
      "Material = benda bernilai fisik, vital = alat untuk beraktivitas, rohani = nilai batin/spiritual.",
  },
  {
    id: 25,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Kasih sayang kepada sesama merupakan contoh...",
    options: ["nilai material", "nilai vital", "nilai rohani", "nilai ekonomi"],
    answer: 2,
    explanation: "Kasih sayang termasuk nilai rohani karena berkaitan dengan batin dan moral.",
  },
  {
    id: 26,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Jika seseorang hanya menghargai kekayaan dan meremehkan orang lain, dampaknya adalah...",
    options: ["solidaritas meningkat", "konflik sosial", "kerja sama lebih baik", "integrasi sempurna"],
    answer: 1,
    explanation: "Mengagungkan nilai material berlebihan cenderung memicu konflik dan merusak tatanan sosial.",
  },
  {
    id: 27,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Kewajiban menggunakan bahasa tertentu di kantor termasuk...",
    options: ["norma", "nilai material", "status sosial", "diferensiasi"],
    answer: 0,
    explanation: "Aturan perilaku di lingkungan tertentu merupakan norma sosial.",
  },
  {
    id: 28,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Norma dengan daya ikat paling kuat adalah...",
    options: ["cara (usage)", "kebiasaan (folkways)", "tata kelakuan (mores)", "adat istiadat"],
    answer: 3,
    explanation: "Adat istiadat memiliki daya ikat sangat kuat karena sudah membudaya dan diwariskan turun-temurun.",
  },
  {
    id: 29,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Nilai yang dianggap baik di suatu daerah tetapi tidak di daerah lain menunjukkan bahwa nilai sosial bersifat...",
    options: ["mutlak", "tetap", "relatif", "universal"],
    answer: 2,
    explanation: "Nilai sosial dipengaruhi konteks budaya sehingga bersifat relatif.",
  },
  {
    id: 30,
    type: "mcq",
    topic: "Nilai dan Norma Sosial",
    prompt: "Menyontek saat ujian melanggar...",
    options: ["norma sosial", "diferensiasi", "mobilitas", "stratifikasi"],
    answer: 0,
    explanation: "Menyontek adalah pelanggaran terhadap norma sosial, khususnya norma kesusilaan dan tata tertib.",
  },

  {
    id: 31,
    type: "multi",
    topic: "Nilai dan Norma Sosial",
    prompt: "Yang termasuk norma dengan daya ikat kuat:",
    options: ["Adat istiadat", "Tata kelakuan", "Cara", "Kebiasaan"],
    answer: [0, 1],
    explanation:
      "Norma yang daya ikatnya kuat adalah tata kelakuan dan adat istiadat, sedangkan cara dan kebiasaan lebih lemah.",
  },
  {
    id: 32,
    type: "multi",
    topic: "Nilai dan Norma Sosial",
    prompt: "Kasus korupsi melanggar...",
    options: ["Norma hukum", "Norma agama", "Norma kesopanan", "Norma kesusilaan"],
    answer: [0, 1, 3],
    explanation:
      "Korupsi melanggar hukum, agama, dan kesusilaan. Norma kesopanan bisa ikut terdampak, tetapi yang paling relevan adalah tiga ini.",
  },

  {
    id: 33,
    type: "mcq",
    topic: "Sosialisasi",
    prompt: "Seorang anak belajar sopan santun dari keluarganya. Ini merupakan sosialisasi...",
    options: ["primer", "sekunder", "represif", "partisipatoris"],
    answer: 0,
    explanation: "Sosialisasi primer terjadi pertama kali dalam keluarga.",
  },
  {
    id: 34,
    type: "mcq",
    topic: "Sosialisasi",
    prompt: "Anak mulai memahami peran sebagai siswa di sekolah. Tahap sosialisasi yang sedang berkembang adalah...",
    options: ["preparatory stage", "play stage", "game stage", "generalized other"],
    answer: 2,
    explanation: "Tahap game stage ditandai kemampuan memahami peran diri dan peran orang lain secara lebih kompleks.",
  },
  {
    id: 35,
    type: "mcq",
    topic: "Sosialisasi",
    prompt: "Tahap ketika seseorang memahami perannya dalam masyarakat luas disebut...",
    options: ["generalized other", "play stage", "imitation stage", "preparatory stage"],
    answer: 0,
    explanation: "Generalized other adalah tahap ketika individu mampu melihat harapan sosial secara umum.",
  },
  {
    id: 36,
    type: "mcq",
    topic: "Sosialisasi",
    prompt: "Jika pengaruh keluarga paling besar terhadap pembentukan karakter, maka agen sosialisasi dominan adalah...",
    options: ["media massa", "teman sebaya", "keluarga", "sekolah"],
    answer: 2,
    explanation: "Keluarga merupakan agen sosialisasi primer dan biasanya paling kuat pengaruhnya.",
  },
  {
    id: 37,
    type: "mcq",
    topic: "Sosialisasi",
    prompt: "Keteladanan siswa di rumah, sekolah, dan masyarakat menunjukkan fungsi sosialisasi berupa...",
    options: ["pewarisan nilai dan norma", "konflik sosial", "diferensiasi sosial", "mobilitas sosial"],
    answer: 0,
    explanation: "Sosialisasi berfungsi mewariskan nilai dan norma agar individu dapat hidup tertib dalam masyarakat.",
  },

  {
    id: 38,
    type: "mcq",
    topic: "Penyimpangan Sosial",
    prompt: "Terlambat masuk sekolah satu kali karena ban bocor termasuk...",
    options: ["penyimpangan primer", "penyimpangan sekunder", "kriminalitas", "kenakalan berat"],
    answer: 0,
    explanation: "Penyimpangan primer bersifat sementara, ringan, dan tidak berulang.",
  },
  {
    id: 39,
    type: "mcq",
    topic: "Penyimpangan Sosial",
    prompt: "Pencurian termasuk bentuk...",
    options: ["konformitas", "penyimpangan sosial", "diferensiasi", "integrasi"],
    answer: 1,
    explanation: "Pencurian adalah perilaku yang menyimpang dari norma sosial.",
  },
  {
    id: 40,
    type: "multi",
    topic: "Penyimpangan Sosial",
    prompt: "Menurut teori Merton, penyimpangan dapat terjadi karena...",
    options: ["Tujuan diterima, cara ditolak", "Tujuan ditolak, cara diterima", "Ketidaksesuaian tujuan dan sarana", "Semua orang memiliki kesempatan sama"],
    answer: [0, 1, 2],
    explanation:
      "Teori anomie Merton menekankan ketidaksesuaian antara tujuan budaya dan sarana yang tersedia.",
  },
  {
    id: 41,
    type: "mcq",
    topic: "Penyimpangan Sosial",
    prompt: "Seorang remaja menjadi pelaku tawuran karena lingkungan pergaulannya. Fenomena ini sesuai teori...",
    options: ["diferensiasi asosiasi", "evolusi", "konflik kelas", "tindakan sosial"],
    answer: 0,
    explanation: "Teori differential association menjelaskan penyimpangan melalui proses belajar dalam pergaulan.",
  },

  {
    id: 42,
    type: "mcq",
    topic: "Pengendalian Sosial",
    prompt: "Pemasangan CCTV bertujuan...",
    options: ["diferensiasi sosial", "pengendalian sosial", "mobilitas sosial", "stratifikasi"],
    answer: 1,
    explanation: "CCTV digunakan untuk memantau dan mengendalikan perilaku sosial.",
  },
  {
    id: 43,
    type: "mcq",
    topic: "Pengendalian Sosial",
    prompt: "Guru menegur siswa yang ribut di kelas. Bentuk pengendalian sosial tersebut bersifat...",
    options: ["preventif", "represif", "koersif", "formal"],
    answer: 1,
    explanation: "Teguran terhadap pelanggaran yang sudah terjadi merupakan pengendalian represif.",
  },
  {
    id: 44,
    type: "mcq",
    topic: "Pengendalian Sosial",
    prompt: "Adanya peraturan lalu lintas berfungsi untuk...",
    options: ["menciptakan keteraturan sosial", "meningkatkan konflik", "membatasi mobilitas sosial", "memperkuat diferensiasi"],
    answer: 0,
    explanation: "Aturan lalu lintas menjaga ketertiban dan keteraturan dalam kehidupan sosial.",
  },
  {
    id: 45,
    type: "mcq",
    topic: "Penyimpangan Sosial",
    prompt: "Seorang siswa mulai merokok karena mengikuti teman-temannya. Faktor penyebab penyimpangan tersebut adalah...",
    options: ["keluarga", "lingkungan pergaulan", "pendidikan tinggi", "mobilitas sosial"],
    answer: 1,
    explanation: "Pengaruh teman sebaya atau lingkungan pergaulan sering menjadi faktor utama penyimpangan.",
  },
];
